config/routes.rb
RoommatesToDo::Application.routes.draw do
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  root 'sessions#new'

  get 'users', :to => 'users#new'

  get 'sessions', :to => 'sessions#new'

  resources :lists do
    resources :items
  end



  
end

app/models/item.rb
class Item
  include Mongoid::Document
  field :name, type: String
  field :quantity, type: String
  field :description, type: String

  belongs_to :list  
end

app/models/list.rb
class List
  include Mongoid::Document
  field :name, type: String

  has_many :items
  
end

app/models/user.rb
require 'bcrypt'

class User
    include Mongoid::Document
    field :name, type: String
    field :email, type: String
    field :password_digest, type: String

    validates_presence_of :name
    validates_presence_of :email

    def password
        @password
    end

    def password=(user_password)
        @password = user_password
        self.password_digest = BCrypt::Password.create(user_password)
    end

    def authenticate(test_password)
        if BCrypt::Password.new(self.password_digest) == test_password
            self
        else
            false
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

include ApplicationHelper

def authenticate_user
    if !self.current_user
      redirect_to new_session_path
      flash[:sign_in] = "Please Sign In."
    end
end

def session_create
    session[:remember_token] = @user.id
    @current_user = @user
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_list

  def index
    @items = @list.items
  end

  def new
    @item = @list.items.new
  end

  def create
    @item = @list.items.create(item_params)
    redirect_to list_path(@list), notice: "You just added #{@item[:name]} to the shopping list."
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to list_path(@list), notice: "You just updated #{@item[:name]}."
    else
      render "edit"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to list_path(@list), notice: "You bought #{@item[:name]}. Thank you!"
  end

  def item_params
    params.require(:item).permit(:name, :quantity, :description) 
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, :only => [:edit, :update, :show, :destroy]
  before_action :authenticate_user

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    redirect_to list_path(@list), notice: "You just added #{@list[:name]}."
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list), notice: "You just updated #{@list[:name]}."
    else
      render "edit"
    end
  end

  def show
  end

  def destroy
    @list.destroy
    redirect_to lists_path, notice: "You deleted #{@list[:name]}."
  end

  protected

  def set_list
    @list = List.find(params[:id])
  end


  def list_params
    params.require(:list).permit(:name) 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

include ApplicationHelper

  def new
  end

  def create
    @user = User.where(:email => params[:session][:email]).first

    if @user && @user.authenticate(params[:session][:password])
      session_create
      redirect_to lists_path
      flash[:notice] = "You have successfully logged in."
    else
      render :new
      flash[:notice] = "Invalid login/password combination. Please try again."
    end

  end

  def destroy
    if session[:remember_token] == nil
      render :new
    else
      @user = User.find(session[:remember_token])
      @user_bye = @user.name.capitalize
      session.delete(:remember_token)  
      flash[:goodbye] = "Goodbye, #{@user_bye}. Come back soon."
      render :new
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session_create
      redirect_to lists_path
      flash[:notice] = "You have successfully signed up!"
    else
        render :new
    end
  end

protected
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user ||= session[:remember_token] && User.find(session[:remember_token])
    end

    def signed_in?
        current_user
    end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

def calculate_age(birthday)
  (Date.today - birthday).to_i / 365
end

end

app/views/items/_form.html.erb
    <%= form_for [@list, @item] do |i| %>
        Item: <%= i.text_field :name, class: "form-control" %>
        Quantity: <%= i.text_field :quantity, class: "form-control" %>
        Description: <%= i.text_field :description, class: "form-control" %>
        <%= i.submit "Submit", class: "btn btn-success" %>
        <div class="clear"></div>
    <% end %>

app/views/items/edit.html.erb
<div class="col-md-4"></div>
    <div class="col-md-4">
        <div class="well well-md">
            <h1>Edit an Item</h1>
       
                <%= render partial: 'items/form' %>

        </div>
    </div>
<div class="col-md-4"></div>

app/views/items/new.html.erb
<div class ="col-md-4"></div>
    <div class ="col-md-4">
        <div class="well well-md">
            <h1>Add an Item to the List</h1>

                <%= render partial: 'items/form' %>

        </div>
    </div>
<div class ="col-md-4"></div>

app/views/items/show.html.erb
<div class="col-md-4"></div>
    <div class="col-md-4">
    <div class="well well-lg">
        <h1><%= @item.name %></h1>
            <p>Quantity: <%= @item.quantity %></p>
            <p>Description: <%= @item.description %></p>

        <%= link_to "Edit this Item", edit_list_item_path(@list, @item), class: "btn btn-info form-control" %>
        <br>
        <%= link_to "Remove This Item From the List", {:action => 'destroy'}, :method => :delete, class: "btn btn-success item-show form-control"  %>
        <div class="clear"></div>
    </div>
</div>
<div class="col-md-4"></div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Roommates Shopping List", lists_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <p class=" navbar-brand">Roommates Shopping List</p> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Log In", new_session_path %></li>
        <% else %>
          <li class="navbar-text">Hello, <%= current_user.name.titleize %></li>
          <li><%= link_to "Add a New Shopping List", new_list_path %></li>
          <li><%= link_to "Log Out", new_session_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>RoommatesToDo</title>
        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    </head>
    
    <body>
        <%= render partial: 'layouts/navbar' %>
        <%= yield %>
    </body>
</html>

app/views/lists/edit.html.erb
<div class="col-md-4"></div>
<div class="well col-md-4">
    <%= form_for @list do |l| %>
        Change the List's Name: <%= l.text_field :name, class: "form-control" %>
        <%= l.submit "Submit", class: "btn btn-success" %>
        <div class="clear"></div>
    <% end %>

</div>
<div class="col-md-4"></div>

app/views/lists/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash.now[:notice] %></div>
<% end %>

<div class="col-md-4"></div>
<div class="well col-md-4">
<h1>The List of Lists</h1>

<% @lists.reverse.each do |l| %>
    <h3><%= link_to l.name, list_path(l) %>
            <%= link_to "Delete This List", list_path(l), :method => :delete, class: "btn btn-danger btn-xs" %>
    </h3>
    <br>
<% end %>
</div>
<div class="col-md-4"></div>

app/views/lists/new.html.erb
<div class="col-md-4"></div>
<div class="well col-md-4">
    <%= form_for @list do |l| %>
        List Name: <%= l.text_field :name, class: "form-control" %>
        <%= l.submit "Submit", class: "btn btn-success" %>
        <div class="clear"></div>
    <% end %>

</div>
<div class="col-md-4"></div>

app/views/lists/show.html.erb
<h1 class="text-center"><%= @list.name.titleize %>
    <br>
    <%= link_to "Add an Item to This List", new_list_item_path(@list), class: "btn btn-success add-item" %>
    <div class="clear"></div>
</h1>
  
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash.now[:notice] %></div>
<% end %>
    <div class="well well-md">
        <table class="table">
                <thead>
                  <tr>
                          <th>Item</th>
                          <th>Quantity</th>
                          <th>Description</th>
                          <th>Buy</th>
                  </tr>
                </thead>

            <tbody>
                  <% @list.items.reverse.each do |g| %>
                    <tr>
                        <td><%= link_to g.name, list_item_path(@list, g) %></td>
                        <td><%= g.quantity %></td>
                        <td><%= g.description %></td>
                        <td id="buy-button"><%= link_to 'Buy It!', list_item_path(@list, g), :method => :delete, class: "btn btn-success btn-xs" %></td>
                    </tr>
                  <% end %>
            </tbody>
        </table>
    </div>

app/views/users/new.html.erb
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <div class="well well-md">
            <h1>Sign Up</h1>
                <%= form_for @user do |f| %>
                    Name: <%= f.text_field :name, class: "form-control" %>
                    Email: <%= f.text_field :email, class: "form-control" %>
                    Password: <%= f.password_field :password, class: "form-control" %>
                    <%= f.submit "Submit", class: "btn btn-success" %>
                <% end %>
                <div class="clear"></div>
        </div>
</div>
    <div class="col-md-4"></div>
</div>